spring:
  datasource:
    url: jdbc:mysql://localhost:3306/car_service_db
    username: root
    password: root_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  liquibase:
    enabled: true

engine-types:
  types:
    - бензиновий
    - дизельний
    - гібридний
    - електричний
fuel-types:
  бензин:
    - А-95
    - А-98
    - А-100
  дизель:
    - зимовий
    - літній
    - арктичний
  електрика: []