engine-types:
  types:
    - бензиновий
    - дизельний
    - гібридний
    - електричний

fuel-types:
  бензин:
    - А-95
    - А-98
    - А-100
  дизель:
    - зимовий
    - літній
    - арктичний
  електрика: []